locale = "en-US"
title = "TAPAAL Documentation"

theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change the default color scheme to one of the variants: "red", "blue", or "green".
  themeVariant = "blue"
